### PR TITLE
Fixed several examples in niupc directory

### PR DESCRIPTION
**Pull request by nixfreak**
Fixed example files in niupc directory

### CODE REVIEW

**Comment by dariolah** [comment]
When using 'niup/niupc' API, you don't need to import 'niup'.

Module 'niup' imports 'niup/niupc' and exports it. By loading 'niup' you get also most of 'niup/niupc' API.
Most because there are some exceptions when exporting 'niup/niupc' from 'niup', e.g. Dialog - same function signature for both modules.

When working with examples in niupc/ directory import only 'niup/niupc' and if needed 'niup/niupext'.

Examples in niup/ directory import only 'niup' module.

**Comment by nixfreak** [comment]
Yes , your right. I started realizing that after I went though the rest of the examples. I will make sure to change them if you haven't already.

**Comment by nixfreak** [comment]
Is there anyway you can separate the niup and nuipc ? Right now since I don't know the full API I would have to compile then look for bugs. Even if I used nuip but still needed the nuipc API.

**Comment by dariolah** [comment]
There are two APIs, modules: ```niup``` and ```niup/niupc```. When using term 'niupc' I'm refering to module ```niup/niupc```

'niupc' can be used standalone.  
This is direct mapping to IUP C API - it uses 'PIhandle' as data type for all controls/classes.  
If you use ```niup/niupc``` API just don't import ```niup```.

Examples in directory niupc/ should NOT use ```import niup```, only use ```import niup/niupc``` and maybe ```import niup/niupext``` and everything should work. 'niupc' has not been changed for long time.

I messed up examples when renaming import from ```niup``` to ```niup/niupc```. Just make sure there is no mention of ```import niup``` and if it compiles it is done.

```niup``` has dependency on 'niupc' and only reason it exports 'niupc' is because of constants, types, etc. which are same for both API-s.
I plan to split 'niupc' then export from niup will not be needed.

If you use ```niup``` API, preferred but still not complete, like examples in niup/ directory, then all you need is ```import niup```.
No need to import or reference niupc.

Also, for both APIs there is no need to use module prefix when calling functions, e.g. ```niupc.Dialog(dlg)```, just ```Dialog(dlg)``` is enough. If there is conflict in function name resolution then it's a bug, and workaround is to specify module prefix.

Documentation is on TODO

**Comment by nixfreak** [comment]
Can I help with documentation? or Something else maybe?

**Comment by dariolah** [comment]
Yes, with documentation, adding missing functions and additional examples for 'niup' and 'niupc'.

'niup' will have a Nim file for each IUP control/class. In each file there will be functions for attributes and callbacks related to that class/control. Initially documentation will be taken from web, without formatting or any Nim specifics e.g. examples of usage.

I plan to have it ready in few weeks.

Then what remains, and I welcome contribution is:
- adding Nim documentation to 'niup' files (Button, Label, ...)
  - module documentation
  - attribute functions doc strings
  - callback functions doc strings (meaning of arguments, using descriptive names for arguments if they are generic arg1, arg2..)
- adding missing functions to 'niup' files
  - some attribute functions are missing
  - some attribute functions can be specialized for types different than string (in case they are not already)
- update README, make it more clear
- additional examples for 'niup' 
  - e.g. copy example from niupc/ and modify it to use 'niup' API
  - rewrite more IUP examples in C to Nim, preferably using 'niup', but using 'niupc' is also OK
- etc.

**Pull request merged**
